### ISSUE TITLE
Previous day is skipped, carry over fails

### ISSUE THREAD

**Issue by proudot** [bastibe/org-journal#189]
Hi,  Sometimes items do not carry over automatically. When that is the case, I noticed that "C-c C-b" skip a day and take me to day-2 instead of day-1. Is there anything non-obvious that could corrupt my day-1 file ? 

Sorry I can't reproduce it easily.

**Comment by cslux** [comment]
Can you post your org-journal setup please.

**Comment by proudot** [comment]
Hi, thanks for your replay! Here is my setup. 
```
(use-package org-journal
  :ensure t
  :defer t
  :custom
  (org-journal-dir "~/ownCloud/journal/")
  (org-journal-find-file 'find-file)
  (org-journal-date-format "%A, %d %B %Y"))
(global-set-key (kbd "C-x C-j") 'org-journal-new-entry)
(setq org-journal-enable-agenda-integration t)
```

**Comment by bastibe** [comment]
I find this can happen if
- you have an unsaved journal file open
- you use the scheduling feature (journal entries in the future)

There's currently no fix for either of these.

**Comment by proudot** [comment]
I am in the second case indeed. I scheduled on event on that day. Let me know how I can help further. I have recently started using org-journal, it is a very useful piece of software. Thanks a ton !

**Comment by bastibe** [comment]
If you'd like to create a pull request, it would be very welcome!

Currently, the function `org-journal-carryover` calls `(org-journal-carryover-items entries prev-buffer)` only once, on `prev-buffer`, which is arrived at using `(org-journal-open-previous-entry 'no-select)` a few lines earlier. 

A good fix would keep calling `org-journal-open-previous-entry` until `entries` are found (or some arbitrary limit, maybe a maximum of five times or so), and only then call `(org-journal-carryover-items entries prev-buffer)`.

**Comment by proudot** [comment]
I am not sure to follow, Isn't it org-journal-open-entry that should be fixed ? (the reverse part)

I just got a look into the functions and I must admit I am a bit confused,  I am not very familiar with elisp.

**Comment by cslux** [comment]
@proudot Do you have some journal files which allows us to reproduce it using your org-journal setup above?

**Comment by bastibe** [comment]
Yes, a test case would be good indeed, to make sure we're all talking about the same thing.

**Comment by cslux** [comment]
I would like to add this issue to the Milestone 2.1.0. However, I don't know what exactly needs to be done to solve this issue. @proudot Are still having issues? Can you share some example journal files for your setup, so we can reproduce it.

**Comment by proudot** [comment]
Hi there,  Sorry I was not responsive, it has been crazy days. I cannot
think of a simple way to reproduce it with a script however. Here are the
steps:

```
1. Make sure you have running todos in your current journal file.
2. (org-journal-new-scheduled-entry)
3. ** pick a day **
4. When this journal day arrives, the TODO item do not carry over.
```

**Comment by cslux** [comment]
Hmm, it's carried-over for me! 

```
* Sunday, 04/05/20
:PROPERTIES:
:CREATED:  [2020-04-05 Sun]
:END:
** TODO zxcvzxcv
** TODO asdfdf
<2020-04-05>
```
Now when I create an entry for today (org-journal-new-entry), the journal file looks like this.

```
* Sunday, 04/05/20
:PROPERTIES:
:CREATED:  [2020-04-05 Sun]
:END:

* Thursday, 04/09/20
:PROPERTIES:
:CREATED:  [2020-04-09 Thu]
:END:
** TODO zxcvzxcv
** TODO asdfdf
<2020-04-05>
** 17:18 works
```

**Comment by proudot** [comment]
Maybe it is different with my setup ? I use one file per day.

````
(use-package org-journal
  :ensure t
  :defer t
  :custom
  (org-journal-dir "~/ownCloud/journal/")
  (org-journal-find-file 'find-file)
  (org-journal-date-format "%A, %d %B %Y"))
(global-set-key (kbd "C-x C-j") 'org-journal-new-entry)
(setq org-journal-enable-agenda-integration t)
````

**Comment by cslux** [comment]
Hmm, works to!

Content of 20200405:
```
* Thursday, 05 April 2020
```
Content of 20200409:
```
* Thursday, 09 April 2020
** TODO asdfdf
<2020-04-05>
** 17:34
```

**Comment by cslux** [comment]
Not sure what else could be wrong! Did you download, org-journal from melpa or melpa-stable?

**Comment by proudot** [comment]
It does carry over in this scenario for me too. But in this scenario it is
carrying over already when we build the scheduled task. In my usecases, I
was scheduling for later days so it was not expected to carry over
immediately. When the day arrives, it does not carry over, It occurred to
me 2 or 3 times. I want to reproduce it again, but the best I can do now is
scheduling something for saturday and waiting two days... Any smarter way ?

**Comment by cslux** [comment]
You could also post some fictive example journal files, showing that behaviour vs. what you would expect.

**Comment by proudot** [comment]
Ok, I will try to reproduce it one last time with the last version to be 100% sure, and save  files snapshot.

**Comment by cslux** [comment]
@proudot If it is happening again, please feel free to reopen it.
