### ISSUE TITLE
Encryption doesn't work with default settings.

### ISSUE THREAD

**Issue by MaikuMori** [bastibe/org-journal#47]
If you enable encryption and use the default journal filename format then Emacs will throw an error because the journal buffer doesn't have org mode enabled and it uses `org-set-tags-to` [here](https://github.com/bastibe/org-journal/blob/master/org-journal.el#L243). `org-set-tags-to` relies on org buffer-local variable which since org-mode is not on is not initialized properly.

I suppose the best fix would be to enable org-mode when opening/creating/operating on journal files. Currently I fixed it by changing `org-journal-file-format` to `%Y-%m-%d.org` (I wanted that anyway so it's fine for me).

**Comment by bastibe** [comment]
Normally, `org-journal` appends the `org-journal-file-pattern` to your `auto-mode-alist` (in the function `org-journal-update-auto-mode-alist`). This runs whenever `org-journal-dir` or `org-journal-file-format` is changed, or when `org-mode` is loaded. With the `auto-mode-alist` entry, journal files are automatically opened in `org-journal-mode` and thus load `org-mode`. This is probably why changing the format solves the problem for you.

However, I can't reproduce your problem on my machine. With encryption enabled and no further customization, I can `C-c C-j` no problem. What version of Emacs and `org-mode` are you running?

**Comment by MaikuMori** [comment]
Emacs version:
`GNU Emacs 24.5.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.16.2)`
Org mode:
`Org-mode version 8.2.10 (8.2.10-42-g2e1bc4-elpaplus @ .../24.5.1/elpa/org-plus-contrib-20150706/)`

I reverted my fix to get the stack trace (upon `C-c C-j`):

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  looking-at(nil)
  org-set-tags-to("crypt")
  org-journal-new-entry(nil)
  call-interactively(org-journal-new-entry nil nil)
  command-execute(org-journal-new-entry)
```

This is how my `org-journal` was setup to produce the stack trace:

```emacs-lisp
(use-package org-journal
  :init
  (setq org-journal-dir "~/Journal"
        ;; org-journal-file-format "%Y-%m-%d.org"
        org-journal-enable-encryption t))
```

Note that `org-journal-dir` is still changed.

**Comment by bastibe** [comment]
If I run Emacs with your settings, I am not getting the error you are describing. However, my file names are all wrong unless I change `org-journal-dir` to `"~/Journal/"` (note the trailing slash). Could this be the problem? This might be messing up your `auto-mode-alist`.

When you run Emacs, but did not interact with org-journal yet, what is the value of `org-journal-file-pattern` and `org-journal-dir`? Also, does your `auto-mode-alist` contain an entry for org-journal-mode? (You can check with `C-h v`)

**Comment by MaikuMori** [comment]
I added the slash and after two restarts it works. Strangely `change->restart` doesn't do anything, but `change->restart->restart` works. Some sort of cache?

```
org-journal-dir is a variable defined in `org-journal.el'.
Its value is "~/Journal/"
Original value was 
"~/Documents/journal/"
```

```
org-journal-file-pattern is a variable defined in `org-journal.el'.
Its value is
"^\\(?1:[0-9]\\{4\\}\\)\\(?2:[0-9][0-9]\\)\\(?3:[0-9][0-9]\\)$"
```

`auto-mode-alist` does have `org-journal` entries: 

```
 ("/home/maiku/Journal/^\\(?1:[0-9]\\{4\\}\\)\\(?2:[0-9][0-9]\\)\\(?3:[0-9][0-9]\\)$" . org-journal-mode)
 ("/home/maiku/Journal/\\(?1:[0-9]\\{4\\}\\)\\(?2:[0-9][0-9]\\)\\(?3:[0-9][0-9]\\)$" . org-journal-mode)
```

The regexes seem a bit odd to me. First one shouldn't work at all. Also according to [this](http://emacswiki.org/emacs/AutoModeAlist) `$` shouldn't be used.

**Comment by bastibe** [comment]
Interesting. I'll put in a fix that appends the slash if it is not there already. That should fix this issue for good. Also, thank you for the heads-up regarding `$`. I'll fix that, too.

Thank you for your help in analyzing this problem. This was very insightful!

**Comment by bastibe** [comment]
OK, this should be fixed in the latest version. Did 1.9.5 solve your issue?

**Comment by MaikuMori** [comment]
Yeah it did. Sorry for delay, I thought I already responded and it turns out I didn't.

Thanks.

**Comment by bastibe** [comment]
Thank you for the bug report, and your help solving this issue.

**Comment by dingmingxin** [comment]
Encryption still not working . Here is my configuration:
```
(setq org-journal-dir "~/wb/journal")
(setq org-journal-file-format "%Y%m%d.org") 
(setq org-journal-enable-encryption t)    
```
If I just added 
```
(setq org-journal-enable-encryption t) 
```
and do not change other settings , Encryption worked well. 
Version Info:
```
GNU Emacs 24.5.1 (x86_64-apple-darwin14.1.0)  
Org-mode version 8.2.10 (release_8.2.10 @ /opt/local/share/emacs/24.5/lisp/org/)
Mac OSX 10.10.3  with gnupg (gpg) command installed
```

**Comment by ejmg** [comment]
This error has mysteriously appeared on my emacs config.

I have the following as my configuration:
```
(setq org-journal-dir "~/home/elias/org/journal/")
(setq org-journal-enable-encryption t)    
```

Before entering/activating a journal entry, `auto-mode-alist` reveals that my configuration for my journal directory is not respected:

```
 ("/home/elias/Documents/journal/\\(?1:[0-9]\\{4\\}\\)\\(?2:[0-9][0-9]\\)\\(?3:[0-9][0-9]\\)\\'" . org-journal-mode)
```

Removing my customized directory made the error go away as it did for @dingmingxin and it works again as expected.

Is there a reason why this would suddenly happen? I just used it yesterday without issue.

I track my dotfiles with version control and reverted edits to my emacs config to see if I could un-break `org-journal` but none of my recent changes involve org-mode and, unsurprisingly, reverting my config file does not fix this. Would deleting my copy of `org-journal` under my `elpa/` directory possibly help?

As always @bastibe, I really appreciate this emacs mode you maintain.

**Comment by bastibe** [comment]
Weird. But thank you for keeping us informed.

**Comment by ejmg** [comment]
Hmm. I've experienced it again.

Switching themes since I last deleted the package and reinstalled it gave me the same error. I will play with this later when I get the chance because I don't think this has anything to do with my two themes I normally use (I have switched between them plenty before).

I am wondering if the recent integration of Fira Fonts or use of a UTF8 symbol in my org-bullet list is triggering this. These feel like much more likely sources of error? I honestly wouldn't know.

**Comment by bastibe** [comment]
With all your customizations, make sure to `setq` your variables before `org-journal` is loaded. Otherwise, it might end up with inconsistent data (or use `customize`, which takes care of this automatically).

Your error message sounds a bit like one of those inconsistent data cases. Also, what is the value of your `org-crypt-tag-matcher`?

**Comment by ejmg** [comment]
> Your error message sounds a bit like one of those inconsistent data cases. Also, what is the value of your org-crypt-tag-matcher?

With my configuration currently functioning as expected, it is:

```
org-crypt-tag-matcher is a variable defined in ‘org-crypt.el’.
Its value is "crypt"
```

> With all your customizations, make sure to setq your variables before org-journal is loaded. Otherwise, it might end up with inconsistent data (or use customize, which takes care of this automatically).

How can I ensure this? I use the org-mode babel trick for maintaining my emacs config. Here's my section for org mode. These are the only edits/configs I have for org mode and org-journal mode:

```
(setq org-bullets-bullet-list (quote ("⬛" "⬤" "▣" "⦿" "►" "◼" "●" "➤")))
;; (setq org-hide-emphasis-markers t)
(setq org-journal-dir "/home/spook/org/journal/")
(setq org-journal-enable-encryption t)

;; stops org-journal from opening previous day's entry
(setq org-journal-carryover-items nil)
;;(emojify-mode 1)
(defun generic-org-minor-modes ()
  (interactive)
  (org-bullets-mode 1)
  (org-cdlatex-mode 1)
  (emojify-mode 1)
  (auto-fill-mode 1))
(add-hook 'org-mode-hook 'generic-org-minor-modes)

;; (setq epa-pinentry-mode 'loopback)
;; (pinentry-start)


;; enable org to evaluate the following PL code blocks with C-c C-c
(org-babel-do-load-languages
 'org-babel-load-languages '((C . t)
                             (python . t)
                             (shell . t)
                             (haskell . t)
                             (emacs-lisp . t)
                             (clojure . t)
                             (js . t)))
```

I would assume org-journal is only loaded upon opening a new entry, i.e. `M-x org-journal-new-entry`. My font changes are triggered at the moment of startup. Should I move my org-mode hook before my org-journal settings? My understanding from how e-lisp evaluation works with respect to emacs configuration is far from good.

Again, thank you for even bothering with this small issue of mine. It means a lot you bother to respond to issues like this and I appreciate it.

**Comment by bastibe** [comment]
No problem. Your config looks good. I don't see an issue there.

Does your `before-save-hook` include `org-journal-encryption-hook`? This is what `org-journal-enable-encryption` is supposed to do.

**Comment by BEpresent** [comment]
Using Spacemacs here, encryption does not seem to work (org-journal itself works, https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bemacs/org#org-journal-support)

`(setq org-journal-enable-encryption t)` is set, may I have forgotten something?
