### ISSUE TITLE
Beginners question: Problems adding org-journal-dir to org-agenda-files

### ISSUE THREAD

**Issue by poulpoulsen** [bastibe/org-journal#92]
hello,
i stuck try to install and configure org-journal.
you wrote
"add all the calendar files to your org-agenda by adding org-journal-dir to org-agenda-files"
therefore i try to customize org-agenda group and insert the variable org-journal-dir as '(org-journal-dir).
But i dont see any journalfile inside my agenda.
After i inside the "real directory" and delete regex i see the files.
i checked the regex
\\`[^.].*\\.org\\'\\|\\`[0-9]+\\'
and find out, that deleting it completely shows them.
Unfortunately after that org complains journal file is no org file. I think because the missing extension *.org.

Any help welcome!
I will try org-journal :-)

Regards
Poul

PS: I'm running emacs 25 with org 9 on windows 8.1 64bit

**Comment by bastibe** [comment]
I can't quite follow the steps you did. Also, I personally don't use org-agenda.

However, if Emacs complains that journal files are not org files, your `auto-mode-alist` is wrong. You can fix this by running `(org-journal-update-auto-mode-alist)`, which should be running automatically whenever in the `org-mode-hook`.

**Comment by gauravsukhija** [comment]
Might it be the regexp?

I used the `Meta-x customize-variable RET org-agenda-file-regexp RET` method to change the variable, and entered in
```
\`[^.].*\.org\'\|\`[0-9]+\'
```

**Comment by poulpoulsen** [comment]
hello,
thank you !
it seems, that it works (files in journal directory with names as dates are recognized) but unfortunately the pure date as filename is not recognized as org-file.
I cannot use the command m-x org-journal-update-auto-mode-alist because my emacs dont know it.
Should i install anything else for that?

Regards
Poul

**Comment by bastibe** [comment]
You should put `(org-journal-update-auto-mode-alist)` somewhere in your init.el. It is not meant to be run interactively. If you absolutely need to, it's `M-x eval-expression [RET] (org-journal-update-auto-mode-alist) [RET]`.

**Comment by cslux** [comment]
I have updated the readme. This should now be more clear.

Putting this in the init file of emacs should work (tested).
``` emacs-lisp
(setq org-agenda-file-regexp "\\`\\\([^.].*\\.org\\\|[0-9]\\\{8\\\}\\\(\\.gpg\\\)?\\\)\\'")
(add-to-list 'org-agenda-files org-journal-dir)
```

**Comment by nano-o** [comment]
I have this problem despite using the lines above in .emacs.
That is, I get there error "Agenda file MYDIR/notes/journal/20190802 is not in Org mode", and indeed the buffers corresponding to those files are not in org-journal mode.
I also tried `M-x eval-expression [RET] (org-journal-update-auto-mode-alist) [RET]`, and it does not fix the problem. 
`auto-mode-alist` contains `(("MYDIR/notes/journal/\\(?1:[0-9]\\{4\\}\\)\\(?2:[0-9][0-9]\\)\\(?3:[0-9][0-9]\\)\\(\\.gpg\\)?\\'" . org-journal-mode)`. Is it correct?
MYDIR is a placeholder for this post.

**Comment by cslux** [comment]
@nano-o Have you tried to reproduce this with =emacs -Q=?

Do you use spacemacs? What org-journal version do you use? What does your org-journal setup look like?

**Comment by nano-o** [comment]
I do not use spacemacs and I have org-journal version 20190914.1643.
My setup looks like this:
```
(require 'package)
(package-initialize)
(require 'org-journal)
(custom-set-variables
 '(initial-buffer-choice "MYDIR/notes/main.org")
 '(org-agenda-file-regexp "\\`\\([^.].*\\.org\\|[0-9]\\{8\\}\\(\\.gpg\\)?\\)\\'")
 '(org-agenda-files
   (quote
    ("MYDIR/notes/journal/" "MYDIR/notes/archive.org" "MYDIR/notes/main.org")))
 '(org-default-notes-file "MYDIR/notes/main.org")
 '(org-directory "MYDIR/notes/")
 '(org-journal-dir "MYDIR/notes/journal/")
```

Will try to reproduce with `emacs -Q` when I get the time.

**Comment by cslux** [comment]
This minimal configuration works for me. 
``` bash
cat <<EOF>> ~/org-journal-setup.el
(add-to-list 'load-path "MYDIR/.emacs.d/elpa/org-journal-20190914.1643")
(require 'org-journal)
(custom-set-variables
 '(initial-buffer-choice "MYDIR/notes/main.org")
 '(org-agenda-file-regexp "\\`\\([^.].*\\.org\\|[0-9]\\{8\\}\\(\\.gpg\\)?\\)\\'")
 '(org-agenda-files
   (quote
    ("MYDIR/emacs/org/journal/")))
 '(org-default-notes-file "MYDIR/emcas/org/main.org")
 '(org-directory "MYDIR/emacs/org/")
 '(org-journal-dir "MYDIR/emacs/org/journal/"))
EOF

emacs -q --load ~/mini-journal-setup.el
```

**Comment by nano-o** [comment]
This minimal config does not work for me: I still get "Agenda file MYDIR/journal/20190802 is not in Org mode"

**Comment by cslux** [comment]
Is your org-journal setup still the same as in https://github.com/bastibe/org-journal/issues/92#issuecomment-532367898?

**Comment by nano-o** [comment]
Yes, still the same.

**Comment by bastibe** [comment]
What is the value of `MYDIR` in your case? Does it include "weird" characters such as umlauts, spaces, or anything else that might trip up Emacs? 

What operating system and version of Emacs are you running?

**Comment by nano-o** [comment]
Sorry, that was obvious: MYDIR points to a directory in a fuse volume managed by Keybase.

**Comment by bastibe** [comment]
Does the problem occur in a "normal" directory as well?

**Comment by nano-o** [comment]
No, the problem does not occur in a "normal" directory.

**Comment by bastibe** [comment]
Interesting. Could you share a short recipe or description of how to set up such a failing path? I'm sure it'll be fixable once one of us can reproduce it.
